DROP TABLE KOLECKIJ.PATIENTS_DOCTORS_CENTER_VISITS;
DROP TABLE KOLECKIJ.DOCTORS_HEALTH_CENTER;
DROP TABLE KOLECKIJ.PATIENTS;
DROP TABLE KOLECKIJ.DOCTORS;
DROP TABLE KOLECKIJ.VISITS;
DROP TABLE KOLECKIJ.USERS;
DROP TABLE KOLECKIJ.HEALTH_CENTER;
DROP TABLE KOLECKIJ.WORKERS;
DROP TABLE KOLECKIJ.WAREHOUSE;
DROP TABLE KOLECKIJ.REDUCTIONS;
DROP TABLE KOLECKIJ.PRESCIPTIONS;
DROP TABLE KOLECKIJ.PHARMACIES;
DROP TABLE KOLECKIJ.MEDICINES;
DROP TABLE KOLECKIJ.DATABASECHANGELOGLOCK;
DROP TABLE KOLECKIJ.DATABASECHANGELOG;

--------------------------------
DROP SEQUENCE KOLECKIJ.DOCTORS_SEQ;
DROP SEQUENCE KOLECKIJ.HEALTH_CENTER_SEQ;
DROP SEQUENCE KOLECKIJ.MEDICINES_SEQ;
DROP SEQUENCE KOLECKIJ.PATIENTS_SEQ;
DROP SEQUENCE KOLECKIJ.PHARMACIES_SEQ;
DROP SEQUENCE KOLECKIJ.PRESCIPTIONS_SEQ;
DROP SEQUENCE KOLECKIJ.REDUCTIONS_SEQ;
DROP SEQUENCE KOLECKIJ.USERS_SEQ;
DROP SEQUENCE KOLECKIJ.VISITS_SEQ;
DROP SEQUENCE KOLECKIJ.WAREHOUSE_SEQ;
DROP SEQUENCE KOLECKIJ.WORKERS_SEQ;