CREATE TABLE KOLECKIJ.DOCTORS_HEALTH_CENTER (
  DOCTOR_ID NUMBER(19),
  HEALTH_CENTER_ID NUMBER(19),
  CONSTRAINT DOCTOR_FK1 FOREIGN KEY (DOCTOR_ID) REFERENCES KOLECKIJ.DOCTORS(ID),
  CONSTRAINT HEALTH_CENTER_FK2 FOREIGN KEY (HEALTH_CENTER_ID) REFERENCES KOLECKIJ.HEALTH_CENTER(ID)
)