CREATE TABLE KOLECKIJ.PATIENTS_DOCTORS_CENTER_VISITS (
  PATIENT_ID NUMBER(19),
  DOCTOR_ID NUMBER(19),
  HEALTH_CENTER_ID NUMBER(19),
  VISIT_ID NUMBER(19),

  CONSTRAINT DOCTOR_P_H_V_FK1 FOREIGN KEY (DOCTOR_ID) REFERENCES KOLECKIJ.DOCTORS(ID),
  CONSTRAINT HEALTH_CENTER_P_D_V_FK2 FOREIGN KEY (HEALTH_CENTER_ID) REFERENCES KOLECKIJ.HEALTH_CENTER(ID),
  CONSTRAINT PATIENT_D_H_V_FK3 FOREIGN KEY (PATIENT_ID) REFERENCES KOLECKIJ.PATIENTS(ID),
  CONSTRAINT VISIT_P_D_H_FK4 FOREIGN KEY (VISIT_ID) REFERENCES KOLECKIJ.VISITS(ID)
)