CREATE TABLE  KOLECKIJ.MEDICINES_PRECIPTIONS(
  MEDICINE_ID NUMBER(19),
  PRECIPTION_ID NUMBER(19),
  CONSTRAINT MEDICINE_P_FK1 FOREIGN KEY (MEDICINE_ID) REFERENCES KOLECKIJ.MEDICINES(ID),
  CONSTRAINT PRECIPTION_M_FK2 FOREIGN KEY (PRECIPTION_ID) REFERENCES KOLECKIJ.PRESCIPTIONS(ID)

)