CREATE TABLE  KOLECKIJ.WORKERS_PRECIPTIONS(
  WORKER_ID NUMBER(19),
  PRECIPTION_ID NUMBER(19),
  CONSTRAINT WORKER_P_FK1 FOREIGN KEY (WORKER_ID) REFERENCES KOLECKIJ.WORKERS(ID),
  CONSTRAINT PRECIPTION_P_FK2 FOREIGN KEY (PRECIPTION_ID) REFERENCES KOLECKIJ.PRESCIPTIONS(ID)
)