CREATE TABLE  KOLECKIJ.WORKERS_PHARMACINES(
  WORKER_ID NUMBER(19),
  PHARMACINE_ID NUMBER(19),
  CONSTRAINT WORKER_PH_FK1 FOREIGN KEY (WORKER_ID) REFERENCES KOLECKIJ.WORKERS(ID),
  CONSTRAINT PHARMACINE_W_FK2 FOREIGN KEY (PHARMACINE_ID) REFERENCES KOLECKIJ.PHARMACIES(ID)
)