CREATE TABLE  KOLECKIJ.WORKERS_PHARMA_WARE_MEDI(
  WORKER_ID NUMBER(19),
  PHARMACINE_ID NUMBER(19),
  WAREHOUSE_ID NUMBER(19),
  MEDICINE_ID NUMBER(19),
  CONSTRAINT WORKER_PH_W_M_FK1 FOREIGN KEY (WORKER_ID) REFERENCES KOLECKIJ.WORKERS(ID),
  CONSTRAINT PHARMACINE_W_W_M_FK2 FOREIGN KEY (PHARMACINE_ID) REFERENCES KOLECKIJ.PHARMACIES(ID),
  CONSTRAINT WAREHOUSE_W_PH_W_M_FK1 FOREIGN KEY (WAREHOUSE_ID) REFERENCES KOLECKIJ.WAREHOUSE(ID),
  CONSTRAINT MEDICINE_W_PH_W_M_FK1 FOREIGN KEY (MEDICINE_ID) REFERENCES KOLECKIJ.MEDICINES(ID)
)