CREATE TABLE  KOLECKIJ.MEDI_REDU_PRESCRI(
  MEDICINE_ID NUMBER(19),
  REDUCTION_ID NUMBER(19),
  PRESCIPTION_ID NUMBER(19),
  CONSTRAINT MEDICINE_R_P_FK1 FOREIGN KEY (MEDICINE_ID) REFERENCES KOLECKIJ.MEDICINES(ID),
  CONSTRAINT REDUCTION_M_P_FK1 FOREIGN KEY (REDUCTION_ID) REFERENCES KOLECKIJ.REDUCTIONS(ID),
  CONSTRAINT PRESCIPTION_M_R_FK1 FOREIGN KEY (PRESCIPTION_ID) REFERENCES KOLECKIJ.PRESCIPTIONS(ID)
)