create type num_array as table of number;
/

CREATE OR REPLACE Function KOLECKIJ.insertWarehouse(
  p_QTY IN KOLECKIJ.WAREHOUSE.ID%TYPE ,
  p_MEDICINE_ID IN KOLECKIJ.WAREHOUSE.ID%TYPE,
  p_PHARMACINE_ID IN KOLECKIJ.WAREHOUSE.ID%TYPE)
  RETURN KOLECKIJ.WAREHOUSE.ID%TYPE
IS
  currIDSeq NUMBER;
  BEGIN
    INSERT INTO KOLECKIJ.WAREHOUSE ("QTY","MEDICINE_ID", "PHARMACINE_ID") VALUES (p_QTY,p_MEDICINE_ID,p_PHARMACINE_ID);
    COMMIT;
    select KOLECKIJ.WAREHOUSE_SEQ.CURRVAL INTO currIDSeq from dual;
    RETURN currIDSeq;
  END;
/
